import React,{useState} from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { C } from '../theme';
import { applyCopilot, copilot } from '../api';
import type { CopilotMode, CopilotResponse } from '../types';
import { Pill } from '../components';

const MODES:CopilotMode[]=['ASK','CONFIGURE','DIAGNOSE','FIX'];
export default function CopilotScreen({onChanged}:{onChanged:()=>void}){
 const [mode,setMode]=useState<CopilotMode>('ASK'); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false); const [result,setResult]=useState<CopilotResponse|null>(null);
 async function send(){if(!message.trim()&&mode!=='DIAGNOSE')return;setBusy(true);try{setResult(await copilot(mode,message||'Check system health'));}catch(e:any){Alert.alert('Copilot',e.message||'Request failed');}finally{setBusy(false);}}
 async function apply(){if(!result?.proposal)return;setBusy(true);try{const r=await applyCopilot(result.proposal.action,result.proposal.value);Alert.alert('Applied',r.message);setResult(null);setMessage('');onChanged();}catch(e:any){Alert.alert('Could not apply',e.message||'Request failed');}finally{setBusy(false);}}
 return <ScrollView style={s.wrap} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.title}>Radar AI Copilot</Text><Text style={s.sub}>Ask, configure, diagnose and perform approval-gated runtime fixes.</Text>
  <View style={s.modes}>{MODES.map(m=><Pressable key={m} onPress={()=>{setMode(m);setResult(null)}}><Pill text={m} tone={mode===m?C.purple:C.border}/></Pressable>)}</View>
  <View style={s.guard}><Text style={s.guardTitle}>Safety gate</Text><Text style={s.guardText}>The AI cannot silently change trading policy or deploy source code. Reversible runtime fixes and configuration changes require your approval.</Text></View>
  <TextInput value={message} onChangeText={setMessage} multiline placeholder={mode==='ASK'?'e.g. Why is CRDO not a BUY?':mode==='CONFIGURE'?'e.g. Change my risk profile to HIGH':mode==='DIAGNOSE'?'e.g. Why has the scanner not updated?':'e.g. Fix the stale scanner'} placeholderTextColor={C.muted} style={s.input}/>
  <Pressable onPress={send} disabled={busy} style={s.send}>{busy?<ActivityIndicator color={C.bg}/>:<Text style={s.sendText}>{mode==='DIAGNOSE'?'Run diagnosis':'Send to Copilot'}</Text>}</Pressable>
  {result?<View style={s.result}><Text style={s.resultMode}>{result.mode}</Text><Text style={s.reply}>{result.reply}</Text>{result.requires_engineering_connector?<Text style={s.note}>Code/deployment repair connector is not enabled in this build.</Text>:null}{result.proposal?<View style={s.proposal}><Text style={s.proposalTitle}>Proposed action</Text><Text style={s.proposalText}>{result.proposal.label}</Text><Pressable onPress={apply} disabled={busy} style={s.apply}><Text style={s.applyText}>Approve & apply</Text></Pressable></View>:null}</View>:null}
 </ScrollView>
}
const s=StyleSheet.create({wrap:{flex:1,backgroundColor:C.bg},content:{padding:16,paddingBottom:120},title:{color:C.text,fontSize:28,fontWeight:'900',marginTop:8},sub:{color:C.muted,fontSize:13,lineHeight:19,marginTop:5},modes:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:18},guard:{backgroundColor:C.panel,borderWidth:1,borderColor:C.purple,borderRadius:16,padding:14,marginTop:14},guardTitle:{color:C.purple,fontWeight:'900'},guardText:{color:C.muted,fontSize:12,lineHeight:18,marginTop:5},input:{backgroundColor:C.panel,color:C.text,minHeight:130,textAlignVertical:'top',borderRadius:18,borderWidth:1,borderColor:C.border,padding:15,marginTop:16},send:{backgroundColor:C.purple,borderRadius:14,padding:14,alignItems:'center',marginTop:10},sendText:{color:C.bg,fontWeight:'900'},result:{backgroundColor:C.panel,borderRadius:18,borderWidth:1,borderColor:C.border,padding:16,marginTop:18},resultMode:{color:C.purple,fontSize:11,fontWeight:'900'},reply:{color:C.text,fontSize:14,lineHeight:21,marginTop:8},note:{color:C.yellow,fontSize:12,lineHeight:18,marginTop:10},proposal:{backgroundColor:C.panel2,borderRadius:14,padding:13,marginTop:14},proposalTitle:{color:C.muted,fontSize:10,fontWeight:'800'},proposalText:{color:C.text,fontWeight:'800',marginTop:5},apply:{backgroundColor:C.green,borderRadius:12,padding:12,alignItems:'center',marginTop:12},applyText:{color:C.bg,fontWeight:'900'}});
