import React,{useState} from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { C } from '../theme';
import { Pill, SectionTitle, signalColor } from '../components';
import type { Bootstrap } from '../types';
import { setRiskProfile } from '../api';

export default function PortfolioScreen({data,refreshing,onRefresh,onOpenStock,onChanged}:{data:Bootstrap;refreshing:boolean;onRefresh:()=>void;onOpenStock:(s:string)=>void;onChanged:()=>void}){
 const [busy,setBusy]=useState(''); async function change(p:string){setBusy(p);try{await setRiskProfile(p);onChanged();}finally{setBusy('');}}
 return <ScrollView style={s.wrap} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={C.green}/>}>
  <Text style={s.title}>Portfolio</Text><View style={s.hero}><Text style={s.heroLabel}>Actual portfolio risk</Text><Text style={s.heroValue}>{Math.round(Number(data.account_risk?.score||0))}/100</Text><Text style={s.heroSub}>Target profile: {data.risk_profile}</Text></View>
  <View style={s.cashRow}><View style={s.cash}><Text style={s.label}>Cash</Text><Text style={s.cashValue}>{Math.round(data.cash).toLocaleString()} {data.base_currency}</Text></View><View style={s.cash}><Text style={s.label}>Reserve</Text><Text style={s.cashValue}>{Math.round(data.reserve).toLocaleString()} {data.base_currency}</Text></View></View>
  <SectionTitle>Risk profile</SectionTitle><View style={s.risks}>{['LOW','MEDIUM','HIGH','AGGRESSIVE'].map(p=><Pressable key={p} onPress={()=>change(p)} disabled={!!busy}><Pill text={busy===p?'…':p} tone={data.risk_profile===p?C.green:C.border}/></Pressable>)}</View>
  <SectionTitle>Holdings</SectionTitle>{data.positions.map(p=><Pressable key={p.id} onPress={()=>onOpenStock(p.symbol)} style={s.position}><View style={s.positionHead}><Text style={s.symbol}>{p.symbol}</Text><Pill text={p.system_signal||p.action||'HOLD'} tone={signalColor(p.system_signal||p.action)}/></View><View style={s.positionRow}><Text style={s.meta}>{p.shares} shares @ {p.avg_cost.toFixed(2)}</Text><Text style={[s.pnl,{color:(p.pnl||0)>=0?C.green:C.red}]}>{p.pnl==null?'—':`${p.pnl>=0?'+':''}${p.pnl.toFixed(1)}%`}</Text></View><Text style={s.meta}>Current {p.currency||''} {Number(p.price||0).toFixed(2)} · Risk {Math.round(Number(p.stock_risk||0))}/100</Text></Pressable>)}
  {data.proposals?.length?<><SectionTitle>Rotation / swap ideas</SectionTitle>{data.proposals.slice(0,5).map((p:any,i:number)=><View key={i} style={s.proposal}><Text style={s.proposalTitle}>{p.title||p.action||'Portfolio proposal'}</Text><Text style={s.meta}>{p.message||p.reason||JSON.stringify(p)}</Text></View>)}</>:null}
 </ScrollView>
}
const s=StyleSheet.create({wrap:{flex:1,backgroundColor:C.bg},content:{padding:16,paddingBottom:120},title:{color:C.text,fontSize:28,fontWeight:'900',marginTop:8},hero:{backgroundColor:C.panel,borderRadius:20,padding:18,borderWidth:1,borderColor:C.border,marginTop:16},heroLabel:{color:C.muted,fontSize:12},heroValue:{color:C.text,fontSize:38,fontWeight:'900',marginTop:4},heroSub:{color:C.cyan,fontWeight:'700',marginTop:4},cashRow:{flexDirection:'row',gap:10,marginTop:10},cash:{flex:1,backgroundColor:C.panel,padding:14,borderRadius:16,borderWidth:1,borderColor:C.border},label:{color:C.muted,fontSize:11},cashValue:{color:C.text,fontWeight:'800',marginTop:4},risks:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:10},position:{backgroundColor:C.panel,padding:15,borderRadius:18,borderWidth:1,borderColor:C.border,marginBottom:10},positionHead:{flexDirection:'row',justifyContent:'space-between'},symbol:{color:C.text,fontSize:20,fontWeight:'900'},positionRow:{flexDirection:'row',justifyContent:'space-between',marginTop:12},meta:{color:C.muted,fontSize:12,lineHeight:18},pnl:{fontSize:14,fontWeight:'800'},proposal:{backgroundColor:C.panel,padding:15,borderRadius:18,borderWidth:1,borderColor:C.yellow,marginBottom:10},proposalTitle:{color:C.yellow,fontWeight:'900',marginBottom:6}});
